db-schema-name: petrol_db

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yaml
    default-schema: ${db-schema-name}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        default_schema: ${db-schema-name}
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petrol_db
    username: root
    password: pass


integration:
  base-url: https://www.nbrb.by
  path: /api/exrates/rates/
  currencies:
    - currency: USD
      id: 431
    - currency: EUR
      id: 451
    - currency: RUR
      id: 456
